version: '3.7'

services:
  database:
    image: mysql
    hostname: ti-mysql
    container_name: ti-mysql
    environment:
      MYSQL_DATABASE: 'transportinfo'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
  message-queue:
    image: vromero/activemq-artemis
    hostname: ti-activemq
    container_name: ti-activemq
    environment:
      ARTEMIS_USERNAME: 'admin'
      ARTEMIS_PASSWORD: 'admin'
    ports:
      - '8161:8161'
      - '61616:61616'
  info:
    build: info/
    hostname: ti-info
    container_name: ti-info
    depends_on:
      - message-queue
    ports:
      - '8080:8080'
  transport:
    build: transport/
    hostname: ti-transport
    container_name: ti-transport
    depends_on:
      - database
      - message-queue
    environment:
      spring.profiles.active: 'docker'
      dbserver: 'ti-mysql'
      dbport: '3306'
      dbuser: 'admin'
      dbpassword: 'admin'
    ports:
      - '3333:8080'
