
package com.tsystems.transportinfo.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Notifications", targetNamespace = "http://soap.transportinfo.tsystems.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Notifications {


    /**
     * 
     * @param driversStat
     */
    @WebMethod
    @RequestWrapper(localName = "updateDriversStat", targetNamespace = "http://soap.transportinfo.tsystems.com/", className = "com.tsystems.transportinfo.soap.UpdateDriversStat")
    @ResponseWrapper(localName = "updateDriversStatResponse", targetNamespace = "http://soap.transportinfo.tsystems.com/", className = "com.tsystems.transportinfo.soap.UpdateDriversStatResponse")
    public void updateDriversStat(
        @WebParam(name = "driversStat", targetNamespace = "")
        DriversStat driversStat);

    /**
     * 
     * @param deliveryList
     */
    @WebMethod
    @RequestWrapper(localName = "updateDeliveryList", targetNamespace = "http://soap.transportinfo.tsystems.com/", className = "com.tsystems.transportinfo.soap.UpdateDeliveryList")
    @ResponseWrapper(localName = "updateDeliveryListResponse", targetNamespace = "http://soap.transportinfo.tsystems.com/", className = "com.tsystems.transportinfo.soap.UpdateDeliveryListResponse")
    public void updateDeliveryList(
        @WebParam(name = "deliveryList", targetNamespace = "")
        DeliveryList deliveryList);

    /**
     * 
     * @param trucksStat
     */
    @WebMethod
    @RequestWrapper(localName = "updateTrucksStat", targetNamespace = "http://soap.transportinfo.tsystems.com/", className = "com.tsystems.transportinfo.soap.UpdateTrucksStat")
    @ResponseWrapper(localName = "updateTrucksStatResponse", targetNamespace = "http://soap.transportinfo.tsystems.com/", className = "com.tsystems.transportinfo.soap.UpdateTrucksStatResponse")
    public void updateTrucksStat(
        @WebParam(name = "trucksStat", targetNamespace = "")
        TrucksStat trucksStat);

}
