
package com.tsystems.transportinfo.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotificationsService", targetNamespace = "http://soap.transportinfo.tsystems.com/", wsdlLocation = "http://ti-info:8080/info/NotificationsServiceLocal?wsdl")
public class NotificationsService
    extends Service
{

    private final static URL NOTIFICATIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTIFICATIONSSERVICE_EXCEPTION;
    private final static QName NOTIFICATIONSSERVICE_QNAME = new QName("http://soap.transportinfo.tsystems.com/", "NotificationsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ti-info:8080/info/NotificationsServiceLocal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFICATIONSSERVICE_WSDL_LOCATION = url;
        NOTIFICATIONSSERVICE_EXCEPTION = e;
    }

    public NotificationsService() {
        super(__getWsdlLocation(), NOTIFICATIONSSERVICE_QNAME);
    }

    public NotificationsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFICATIONSSERVICE_QNAME, features);
    }

    public NotificationsService(URL wsdlLocation) {
        super(wsdlLocation, NOTIFICATIONSSERVICE_QNAME);
    }

    public NotificationsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFICATIONSSERVICE_QNAME, features);
    }

    public NotificationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Notifications
     */
    @WebEndpoint(name = "NotificationsImplPort")
    public Notifications getNotificationsImplPort() {
        return super.getPort(new QName("http://soap.transportinfo.tsystems.com/", "NotificationsImplPort"), Notifications.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Notifications
     */
    @WebEndpoint(name = "NotificationsImplPort")
    public Notifications getNotificationsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.transportinfo.tsystems.com/", "NotificationsImplPort"), Notifications.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFICATIONSSERVICE_EXCEPTION!= null) {
            throw NOTIFICATIONSSERVICE_EXCEPTION;
        }
        return NOTIFICATIONSSERVICE_WSDL_LOCATION;
    }

}
