
package com.tsystems.transportinfo.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Notifications", targetNamespace = "http://soap.transportinfo.tsystems.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Notifications {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateDriversStat", targetNamespace = "http://soap.transportinfo.tsystems.com/", className = "com.tsystems.transportinfo.UpdateDriversStat")
    @ResponseWrapper(localName = "updateDriversStatResponse", targetNamespace = "http://soap.transportinfo.tsystems.com/", className = "com.tsystems.transportinfo.UpdateDriversStatResponse")
    public void updateDriversStat(
        @WebParam(name = "arg0", targetNamespace = "")
        DriversStat arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateTrucksStat", targetNamespace = "http://soap.transportinfo.tsystems.com/", className = "com.tsystems.transportinfo.UpdateTrucksStat")
    @ResponseWrapper(localName = "updateTrucksStatResponse", targetNamespace = "http://soap.transportinfo.tsystems.com/", className = "com.tsystems.transportinfo.UpdateTrucksStatResponse")
    public void updateTrucksStat(
        @WebParam(name = "arg0", targetNamespace = "")
        TrucksStat arg0);

}
